---
title: "Forest Plots"
output: 
  html_document:
    toc: true
    number_sections: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    toc_depth: 3
editor_options: 
  chunk_output_type: console
---

```{r, eval = TRUE}
knitr::opts_knit$set(root.dir = "../../")
```


```{r}
suppressPackageStartupMessages(library(tidyverse))
library(gt)
library(targets)
source("src/R/forest_plots.R")
```


# Forest Plots

```{r df_fores}
df_forest <- tar_read(df_forest)

df_forest
```


## Consent

```{r cnsn, eval = TRUE, warning=FALSE}
df_forest %>%
  filter(category_id == "cnsn") %>%
  pull(tab) %>%
  htmltools::tagList()
```

## Data Integrity

```{r dtin, eval = TRUE, warning=FALSE}
df_forest %>%
  filter(category_id == "dtin") %>%
  pull(tab) %>%
  htmltools::tagList()
```

## Safety

```{r sfty, eval = TRUE, warning=FALSE}
df_forest %>%
  filter(category_id == "sfty") %>%
  pull(tab) %>%
  htmltools::tagList()
```

## Protecting Endpoints

```{r ptpe, eval = TRUE, warning=FALSE}
df_forest %>%
  filter(category_id == "ptpe") %>%
  pull(tab) %>%
  htmltools::tagList()
```