# Generated by targets: do not edit by hand
library(targets)
lapply(
  list.files(
    file.path("_targets_r", "globals"),
    pattern = "\\.R$",
    full.names = TRUE
  ),
  source
)
lapply(
  list.files(
    file.path("_targets_r", "targets"),
    pattern = "\\.R$",
    full.names = TRUE
  ),
  function(x) source(x)$value
)
